[package]
name = "rust-test"
version = "0.1.0"
edition = "2024"

[dependencies]
x11rb = { version = "0.13", features = ["allow-unsafe-code","all-extensions"] }
gl = "0.14"
libc = "0.2"
glam = "0.30.8"